M48
; DRILL file {KiCad 7.0.8} date Sat 11 Nov 2023 08:44:46 PM WAT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-11T20:44:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X138.43Y-101.6
X151.13Y-101.6
T2
X165.1Y-101.6
X167.64Y-101.6
T0
M30
